// <auto-generated />
namespace Smorgaschord_Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CustomLessonBeginning : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomLessonBeginning));
        
        string IMigrationMetadata.Id
        {
            get { return "201706151952059_CustomLessonBeginning"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
